__title__ = 'Geo km'
__description__ = 'Calculate distance and travel time between points using Google API.'
__url__ = 'not available'
__version__ = '2.0'
__author__ = 'Shkaberda V., Zubriichuk V.'
__author_email__ = 'not available'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2021 Shkaberda Vadim, Vitaliy Zubriichuk'